
server:
  port: 8080
spring:
  application:
    name: demo-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8000/eureka}

#feign配置
#feign:
#  client:
#    config:
#      service:
#        #开启日志。
#        loggerLevel: FULL

feign:
  hystrix:
    enabled: true #为Feign开启Hystrix

hystrix:
  command:
    default:
      circuitBreaker:
        errorThresholdPercentage: 50 # 触发熔断的错误比例
        sleepWindowMilliseconds: 100000 # 熔断后的休眠时间，单位：毫秒，即熔断开启到正常访问服务的时间间隔
        requestVolumeThreshold: 2 # 触发熔断的最小请求次数
      execution:
        #超时时间开启
        timeout:
          enabled: true
        #隔离策略
        isolation:
          strategy: THREAD # 隔离策略：线程隔离
          thread:
            timeoutInMilliseconds: 1000 # 线程超时时间：1秒后，调用Fallback
#ribbon:
#  ConnectTimeout: 2000 # 服务连接超时时间，单位：毫秒
#  ReadTimeout: 3000 # 获取响应超时时间，单位：毫秒，不可大于Hystrix超时时间
#  MaxAutoRetries: 0 # 最大自动重试次数
#  MaxAutoRetriesNextServer: 0 # 向集群其他服务最大重试次数

logging:
  level:
    # Fegin 日志以社么级别监听哪个接口
    com.padingpading.consumer.feign.ProducerFeignClient: debug