
server:
  port: 8080
spring:
  application:
    name: demo-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8000/eureka}

#feign配置
feign:
  client:
    config:
      service:
        #开启日志。
        loggerLevel: FULL

logging:
  level:
    # Fegin 日志以社么级别监听哪个接口
    com.padingpading.consumer.feign.ProducerFeignClient: debug